### ISSUE TITLE
[Bug]: Does not work on NeoForge and Sintrya Connector

### ISSUE THREAD

**Issue by Jouto25** [sisby-folk/tinkerers-smithing#59] opened 2024-12-20 04:22 UTC
It appears that Tinker's Smithing does not work with NeoForge and the Sintrya Connector. 

MC Version: 1.21.1
NeoForge Version: 21.1.90

Mod list:
  [✔] c2me-neoforge-mc1.21.1-0.3.0+alpha.0.32
  [✔] connector-2.0.0-beta.4+1.21.1-full
  [✔] continuity-3.0.0+1.21.neoforge
  [✔] entityculling-neoforge-1.7.2-mc1.21
  [✔] ferritecore-7.0.2-neoforge
  [✔] forgified-fabric-api-0.107.0+2.0.22+1.21.1
  [✔] iris-neoforge-1.8.1+mc1.21.1
  [✔] lithium-neoforge-0.14.3-snapshot+mc1.21.1-build.92
  [✔] modernfix-neoforge-5.19.6+mc1.21.1
  [✔] reeses-sodium-options-neoforge-1.8.0+mc1.21.3
  [✔] sodium-neoforge-0.6.5+mc1.21.1
  [✔] tinkerers-smithing-2.7.0+1.21

Logs: [tinkerslogs.txt](https://github.com/user-attachments/files/18205907/tinkerslogs.txt)

**Comment by sisby-folk** [comment] 2024-12-23 23:57
dupe of #58

**Closed as not planned by sisby-folk** 2024-12-23 23:57 UTC
