### ISSUE TITLE
Elaytra Brokes on flight

### ISSUE THREAD

**Issue by gabrielpgava** [sisby-folk/tinkerers-smithing#52] opened 2024-10-01 15:48 UTC
I encountered an issue with a mod on a server with friends where the Elytra would break instantly upon attempting to fly. Is there a known fix for this problem, or could it be an issue with the mod itself? I really enjoy the mod, but this issue has compelled me to remove it.

**Comment by sisby-folk** [comment] 2024-10-01 15:50
duplicate of #46 I think

**Closed as not planned by sisby-folk** 2024-10-01 15:50 UTC
