### ISSUE TITLE
Sinytra Connector Crash - client.InGameHudMixin fails to inject

### ISSUE THREAD

**Issue by Dakedres** [sisby-folk/tinkerers-smithing#24] opened 2023-12-06 06:31 UTC
I added Tinkerer's Smithing 2.5.1 to my modpack, with the latest FFAPI and Connector versions,. Crashes at startup with a failed mixin injection.

> Critical injection failure: Variable modifier method showBrokenHeldItemTooltip(Lnet/minecraft/network/chat/MutableComponent;)Lnet/minecraft/network/chat/MutableComponent; in tinkerers_smithing.mixins.json:client.InGameHudMixin from mod tinkerers_smithing failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap tinkerers_smithing-refmap.json

[Full log](https://mclo.gs/61e2poF)

**Comment by sisby-folk** [comment] 2023-12-29 02:19
Not a critical mixin, so you can manually drop it from the list if need be as a workaround - we'll keep an eye on this and see if it goes away after some upcoming reworks.

**Comment by sisby-folk** [comment] 2024-01-06 02:46
![image](https://github.com/sisby-folk/tinkerers-smithing/assets/55819817/fce3119e-1b44-4b22-a1e8-003d5e49a8f7)

can't reproduce on latest - can you check this again?

**Comment by sisby-folk** [comment] 2024-01-14 23:07
closing this for now, let us know if it comes back up.

**Comment by Dakedres** [comment] 2024-02-21 07:02
I've been able to reproduce again on 2.6.7, occured on a seperate pack I tried recently, here it is in an isolated instance:
[https://mclo.gs/TzhLcya](https://mclo.gs/TzhLcya)

**Comment by IAKamil** [comment] 2024-04-23 10:52
I've got the same problem, with an isolated instance producing the same Injection Failure for showBrokenHeldItemTooltip

**Comment by sisby-folk** [comment] 2024-04-28 04:57
Still can't reproduce gang, not really sure what's going on here

https://mclo.gs/K4DX95x

![image](https://github.com/sisby-folk/tinkerers-smithing/assets/55819817/f9e8b8b4-5183-44b4-8835-7a2f31451ec5)

![image](https://github.com/sisby-folk/tinkerers-smithing/assets/55819817/e90dc58b-4ab7-4b30-a650-e8fddec0e128)

The mixin in question doesn't _work_ (the held item tooltip remains unmodified) but doesn't crash in my instance.

**Comment by sisby-folk** [comment] 2024-04-28 05:23
bit the bullet and decided to solve this by throwing myself at the mixin until i had a version that actually _worked_ on forge, which should guarantee that it doesn't crash by extension - have fun!

![image](https://github.com/sisby-folk/tinkerers-smithing/assets/55819817/4e9b5a14-10d9-4442-89fb-0a2ecf53e96f)

**Closed as completed** 2024-04-28 05:23 UTC
Labels: bug

**Comment by IAKamil** [comment] 2024-04-29 05:44
That's Great, Thanks
